"""empty message

Revision ID: 0c1bc66c1fb0
Revises: 9edd012b21db
Create Date: 2025-05-04 13:37:05.550573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1bc66c1fb0'
down_revision = '9edd012b21db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_predictions', sa.Column('historical_avg_daily_order', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_predictions', 'historical_avg_daily_order')
    # ### end Alembic commands ###
