"""Add reminder state tracking

Revision ID: 0cdee773db7f
Revises: 0c1bc66c1fb0
Create Date: 2025-05-05 09:58:28.467016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cdee773db7f'
down_revision = '0c1bc66c1fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_predictions', sa.Column('customer_email', sa.String(length=255), nullable=True))
    op.add_column('account_predictions', sa.Column('reminder_state', sa.String(length=20), nullable=True))
    op.add_column('account_predictions', sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_account_predictions_reminder_sent_at'), 'account_predictions', ['reminder_sent_at'], unique=False)
    op.create_index(op.f('ix_account_predictions_reminder_state'), 'account_predictions', ['reminder_state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_predictions_reminder_state'), table_name='account_predictions')
    op.drop_index(op.f('ix_account_predictions_reminder_sent_at'), table_name='account_predictions')
    op.drop_column('account_predictions', 'reminder_sent_at')
    op.drop_column('account_predictions', 'reminder_state')
    op.drop_column('account_predictions', 'customer_email')
    # ### end Alembic commands ###
