"""Add distributor_item_code to Transaction model

Revision ID: 621458da5a3b
Revises: 0dbb658c8bbd
Create Date: 2025-08-19 15:34:55.340343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '621458da5a3b'
down_revision = '0dbb658c8bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_mapping')
    op.add_column('transactions', sa.Column('distributor_item_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'distributor_item_code')
    op.create_table('product_mapping',
    sa.Column('name_clean', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sku_list', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name_clean', name=op.f('product_mapping_tmp_pkey'))
    )
    # ### end Alembic commands ###
