"""Add transaction hash column

Revision ID: 9da4b3183213
Revises: f0ff30f9ea51
Create Date: 2025-06-24 12:02:29.646461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da4b3183213'
down_revision = 'f0ff30f9ea51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_transactions_transaction_hash'), 'transactions', ['transaction_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_hash'), table_name='transactions')
    op.drop_column('transactions', 'transaction_hash')
    # ### end Alembic commands ###
