"""Add rep_last_order fields

Revision ID: 9edd012b21db
Revises: 7d66f37f129b
Create Date: 2025-05-04 11:19:45.600833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9edd012b21db'
down_revision = '7d66f37f129b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_predictions', sa.Column('rep_last_order_date', sa.DateTime(), nullable=True))
    op.add_column('account_predictions', sa.Column('rep_last_order_amount', sa.Float(), nullable=True))
    op.create_index(op.f('ix_account_predictions_rep_last_order_date'), 'account_predictions', ['rep_last_order_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_predictions_rep_last_order_date'), table_name='account_predictions')
    op.drop_column('account_predictions', 'rep_last_order_amount')
    op.drop_column('account_predictions', 'rep_last_order_date')
    # ### end Alembic commands ###
