"""add_item_code_to_transaction_and_sku_product_lists

Revision ID: d16aa733fd65
Revises: 0cdee773db7f
Create Date: 2025-05-19 13:24:04.455830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16aa733fd65'
down_revision = '0cdee773db7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_predictions', sa.Column('notified_last_purchase_date', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('item_code', sa.String(length=50), nullable=True))
    op.create_index('idx_transaction_item_code', 'transactions', ['item_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transaction_item_code', table_name='transactions')
    op.drop_column('transactions', 'item_code')
    op.drop_column('account_predictions', 'notified_last_purchase_date')
    # ### end Alembic commands ###
