"""Add rolling_sku_analysis_json to AccountPrediction

Revision ID: e060ca9297de
Revises: 9da4b3183213
Create Date: 2025-07-22 05:55:10.408964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e060ca9297de'
down_revision = '9da4b3183213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_predictions', sa.Column('rolling_sku_analysis_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_predictions', 'rolling_sku_analysis_json')
    # ### end Alembic commands ###
