"""Add revenue_trend_intercept to AccountPrediction

Revision ID: f0ff30f9ea51
Revises: ff7d26173c49
Create Date: 2025-05-21 21:34:39.136895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ff30f9ea51'
down_revision = 'ff7d26173c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_predictions', sa.Column('revenue_trend_intercept', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_predictions', 'revenue_trend_intercept')
    # ### end Alembic commands ###
