"""add_trend_and_growth_engine_fields

Revision ID: ff7d26173c49
Revises: d16aa733fd65 
Create Date: 2025-05-21 18:04:46.730898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff7d26173c49'
down_revision = 'd16aa733fd65' # Make sure this points to your PREVIOUS migration
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_predictions', sa.Column('revenue_trend_slope', sa.Float(), nullable=True))
    op.add_column('account_predictions', sa.Column('revenue_trend_r_squared', sa.Float(), nullable=True))
    
    # --- ADD GROWTH ENGINE FIELDS ---
    op.add_column('account_predictions', sa.Column('target_yep_plus_1_pct', sa.Float(), nullable=True))
    op.add_column('account_predictions', sa.Column('additional_revenue_needed_eoy', sa.Float(), nullable=True)) # Corrected spelling
    op.add_column('account_predictions', sa.Column('suggested_next_purchase_amount', sa.Float(), nullable=True))
    op.add_column('account_predictions', sa.Column('recommended_products_next_purchase_json', sa.Text(), nullable=True)) # Use sa.Text for JSON strings
    op.add_column('account_predictions', sa.Column('growth_engine_message', sa.String(length=500), nullable=True)) # Adjust length as needed
    op.add_column('account_predictions', sa.Column('avg_purchase_cycle_days', sa.Float(), nullable=True))
    # --- END GROWTH ENGINE FIELDS ---
    
    op.create_index(op.f('ix_transactions_item_code'), 'transactions', ['item_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_item_code'), table_name='transactions')

    # --- DROP GROWTH ENGINE FIELDS (in reverse order of addition) ---
    op.drop_column('account_predictions', 'avg_purchase_cycle_days')
    op.drop_column('account_predictions', 'growth_engine_message')
    op.drop_column('account_predictions', 'recommended_products_next_purchase_json')
    op.drop_column('account_predictions', 'suggested_next_purchase_amount')
    op.drop_column('account_predictions', 'additional_revenue_needed_eoy') # Corrected spelling
    op.drop_column('account_predictions', 'target_yep_plus_1_pct')
    # --- END DROP GROWTH ENGINE FIELDS ---

    op.drop_column('account_predictions', 'revenue_trend_r_squared')
    op.drop_column('account_predictions', 'revenue_trend_slope')
    # ### end Alembic commands ###